# EJERCICIO 3

In [21]:
from wget import download
from os import path, listdir
import pandas as pd

## Implementar en una notebook de Jupyter el código necesario para...

#### I) Descargar automáticamente ambos archivos :

Descargo el archivo que contiene la descripción del material de trabajo:

Ahora, descargo el archivo que contiene los datos:

In [22]:
if not path.exists("catalogo_streaming_argentina_2024.xlsx") :
    download("https://ignaciorlando.github.io/datasets/data-science/catalogo_streaming_argentina_2024.xlsx")
else :
    print("El archivo ya existe")

El archivo ya existe

#### III) Leer el archivo de datos.

Para el siguiente paso, abro el archivo con la libreria de "Pandas":

In [23]:
raw_dataframe = pd.read_excel("catalogo_streaming_argentina_2024.xlsx")

raw_dataframe

,title,platform,type,imdbVotes,imdbScore,tmdbPopularity,tmdbScore,runtime,genres,director,year_range,url
0,Cadena perpetua,Max,MOVIE,2906253.0,9.3,159.594,8.705,142,"Drama, Crimen",Frank Darabont,1900_2002,https://play.max.com/movie/9b4dacba-2f80-4272-...
1,El caballero oscuro,Max,MOVIE,2893241.0,9.0,111.674,8.516,152,"Misterio & Suspense, Drama, Acción & Aventura,...",Christopher Nolan,2003_2010,https://play.max.com/movie/52217243-a137-45d6-...
2,Origen,Max,MOVIE,2570263.0,8.8,139.644,8.369,148,"Ciencia ficción, Acción & Aventura, Misterio &...",Christopher Nolan,2003_2010,https://play.max.com/movie/14552c93-d318-4563-...
3,El club de la lucha,Disney Plus,MOVIE,2345071.0,8.8,108.297,8.400,139,Drama,David Fincher,1998_2004,https://disneyplus.bn5x.net/c/1206980/705874/9...
4,El club de la lucha,Netflix,MOVIE,2345071.0,8.8,108.297,8.400,139,Drama,David Fincher,1995_2005,http://www.netflix.com/title/26004747
...,...,...,...,...,...,...,...,...,...,...,...,...
19812,Три кота,Netflix,SHOW,NaN,NaN,13.684,5.400,5,Ciencia ficción,NaN,2013_2017,http://www.netflix.com/title/81208524
19813,أم الدراهم,Amazon Prime Video,SHOW,NaN,NaN,0.858,NaN,29,Comedia,NaN,2021,https://app.primevideo.com/detail?gti=amzn1.dv...
19814,ورق مسموم,Amazon Prime Video,SHOW,NaN,NaN,0.600,NaN,48,NaN,NaN,2022,https://app.primevideo.com/detail?gti=amzn1.dv...
19815,ガクドリ,Amazon Prime Video,MOVIE,NaN,NaN,2.841,NaN,90,NaN,Kei Era,2011_2013,https://app.primevideo.com/detail?gti=amzn1.dv...
19816,新歌舞伎：赤胴鈴之助,Netflix,MOVIE,NaN,NaN,3.203,NaN,169,Fantasía,Kikunojo Onoe,2022,http://www.netflix.com/title/81517566

#### IV) Imprimir la cabecera del archivo

In [24]:
raw_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19817 entries, 0 to 19816
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           19817 non-null  object
 1   platform        19817 non-null  object
 2   type            19817 non-null  object
 3   imdbVotes       17854 non-null  float64
 4   imdbScore       17927 non-null  float64
 5   tmdbPopularity  19538 non-null  float64
 6   tmdbScore       18954 non-null  float64
 7   runtime         19817 non-null  int64
 8   genres          19665 non-null  object
 9   director        14626 non-null  object
 10  year_range      19817 non-null  object
 11  url             19817 non-null  object
dtypes: float64(4), int64(1), object(7)
memory usage: 1.8+ MB

#### V) Imprimir los primeros 5 registros del archivo.

In [25]:
raw_dataframe.head()

,title,platform,type,imdbVotes,imdbScore,tmdbPopularity,tmdbScore,runtime,genres,director,year_range,url
0,Cadena perpetua,Max,MOVIE,2906253.0,9.3,159.594,8.705,142,"Drama, Crimen",Frank Darabont,1900_2002,https://play.max.com/movie/9b4dacba-2f80-4272-...
1,El caballero oscuro,Max,MOVIE,2893241.0,9.0,111.674,8.516,152,"Misterio & Suspense, Drama, Acción & Aventura,...",Christopher Nolan,2003_2010,https://play.max.com/movie/52217243-a137-45d6-...
2,Origen,Max,MOVIE,2570263.0,8.8,139.644,8.369,148,"Ciencia ficción, Acción & Aventura, Misterio &...",Christopher Nolan,2003_2010,https://play.max.com/movie/14552c93-d318-4563-...
3,El club de la lucha,Disney Plus,MOVIE,2345071.0,8.8,108.297,8.400,139,Drama,David Fincher,1998_2004,https://disneyplus.bn5x.net/c/1206980/705874/9...
4,El club de la lucha,Netflix,MOVIE,2345071.0,8.8,108.297,8.400,139,Drama,David Fincher,1995_2005,http://www.netflix.com/title/26004747

#### VI) Imprimir el resumen estadístico del mismo

In [26]:
raw_dataframe.describe(include="all")

,title,platform,type,imdbVotes,imdbScore,tmdbPopularity,tmdbScore,runtime,genres,director,year_range,url
count,19817,19817,19817,1.785400e+04,17927.000000,19538.000000,18954.000000,19817.000000,19665,14626,19817.0,19817
unique,18008,6,2,NaN,NaN,NaN,NaN,NaN,4189,8812,27.0,19062
top,La niñera,Netflix,MOVIE,NaN,NaN,NaN,NaN,NaN,Documental,Steven Spielberg,2022.0,http://www.netflix.com/title/81516046
freq,5,7109,14060,NaN,NaN,NaN,NaN,NaN,1277,27,1697.0,2
mean,NaN,NaN,NaN,4.838858e+04,6.399520,41.195589,6.461363,80.542867,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,1.488473e+05,1.200258,131.031366,1.254487,37.092943,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,5.000000e+00,1.100000,0.001000,0.500000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,4.620000e+02,5.700000,5.433250,5.889500,48.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,2.849500e+03,6.500000,14.428500,6.600000,89.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2.196975e+04,7.300000,33.312500,7.273750,105.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,2.906253e+06,9.700000,4173.518000,10.000000,263.000000,NaN,NaN,NaN,NaN

## Analizar los valores de las columnas. ¿Qué tipo de datos hay en cada una? ¿Qué representan? Incluir información del análisis en la notebook.

- **TITLE:** dato cualitativo nominal. Guarda el titulo de la pelicula o serie, puede servir para saber qué títulos son llamativos o conocidos.
- **PLATFORM:** dato cualitativo nominal. Se refiere a la plataforma de streaming donde se encuentra la serie o pelicula, lo que puede ser útil para ver el rendimiento de las plataformas.
- **TYPE:** dato cualitativo nominal. Representa el tipo de producto: si es una pelicula o serie.
- **IMDBVOTES:** dato cuantitativo discreto. Se refiere a la gente que votó en IMDB.                            
- **IMDBSCORE:** dato cuantitativo continuo. Indica el puntaje del filme en IMDb.
- **TMDBPOPULARITY:** dato cuantitativo continuo. Muestra un índice de popularidad.                     
- **TMDBSCORE:** dato cuantitativo continuo. Indica el puntaje de la película en TMDb.                          
- **RUNTIME:** dato cuantitativo discreto. Se refiere a la duración del producto.                          
- **GENRES:** dato cualitativo nominal. Indica el género de la obra.                        
- **DIRECTOR:** dato cuantitativo nominal. El director podría indicarnos tendencias de la gente.        
- **YEAR_RANGE:** dato cualitativo ordinal. Puede referirse al rango de años en los cuales está ambientado el producto.
- **URL:** dato cualitativo nominal.

## Proponer una serie de análisis propios:

#### I) ¿Cuántos directores distintos hay?

In [27]:
frecuencia_directores = raw_dataframe["director"].value_counts() 

num_directores = frecuencia_directores.shape[0]
print(f"La cantidad de directores: {num_directores}\n")
print(f"Los directores en orden según la cantidad de veces que aparecen:\n\n{frecuencia_directores}\n")

La cantidad de directores: 8812

Los directores en orden según la cantidad de veces que aparecen:

director
Steven Spielberg    27
Woody Allen         24
Pedro Almodóvar     21
Michael Bay         21
Robert Vince        19
                    ..
Anthony Burns        1
Jee Hye-won          1
René Cardona III     1
Tobi Baumann         1
Hideaki Takizawa     1
Name: count, Length: 8812, dtype: int64

#### II) ¿Quién es el director con más películas?

In [28]:
director_repetido = raw_dataframe["director"].mode()[0] 
print(f"El director más repetido es: {director_repetido}")

El director más repetido es: Steven Spielberg

#### III) ¿Cuántas series hay? ¿Y cuántos programas de TV?

In [30]:
cant_programas = raw_dataframe[raw_dataframe["type"] == "TV Show"].shape[0]
print(f"La cantidad de programas es: {cant_programas}")

cant_series = raw_dataframe[raw_dataframe["listed_in"].str.contains("series", case=False)].shape[0]
print(f"La cantidad de series es: {cant_series}")

La cantidad de programas es: 0

KeyError: 'listed_in'

#### IV) ¿Cuál es la película más vieja del catálogo? ¿Y la serie?

In [ ]:
fecha_mas_vieja = raw_dataframe["release_year"].min()
peliculas_mas_viejas = raw_dataframe[raw_dataframe["release_year"] == fecha_mas_vieja]
peliculas_mas_viejas

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### V) Dado un país, determinar cuántas películas de ese país hay en la base de datos

In [ ]:
pais = input("Ingrese un país:")
cant_pais = raw_dataframe[raw_dataframe["country"].str.casefold() == pais.casefold()].shape[0]
print(f"El país que elegiste aparece {cant_pais} veces")

Ingrese un país: United States

El país que elegiste aparece 2819 veces